/* tslint:disable */
/* eslint-disable */
/**
 * ShanyLedger App
 * これはShanyLedgerのAPIサーバーの仕様です。
 *
 * The version of the OpenAPI document: 0.0.8
 * Contact: support@shany-ledger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { User } from './user';

/**
 * サインアップが成功した場合のレスポンスボディです。
 * @export
 * @interface AuthSignupSuccessResponse
 */
export interface AuthSignupSuccessResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthSignupSuccessResponse
     */
    'accessToken'?: string;
    /**
     * 
     * @type {User}
     * @memberof AuthSignupSuccessResponse
     */
    'user'?: User;
}

