/* tslint:disable */
/* eslint-disable */
/**
 * ShanyLedger App
 * これはShanyLedgerのAPIサーバーの仕様です。
 *
 * The version of the OpenAPI document: 0.0.8
 * Contact: support@shany-ledger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * メールアドレスとパスワードを使用したサインアップのリクエストボディです。
 * @export
 * @interface AuthSignupRequest
 */
export interface AuthSignupRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthSignupRequest
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof AuthSignupRequest
     */
    'password': string;
}

