/* tslint:disable */
/* eslint-disable */
/**
 * ShanyLedger App
 * これはShanyLedgerのAPIサーバーの仕様です。
 *
 * The version of the OpenAPI document: 0.0.8
 * Contact: support@shany-ledger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BadGatewayErrorAllOf
 */
export interface BadGatewayErrorAllOf {
    /**
     * 
     * @type {number}
     * @memberof BadGatewayErrorAllOf
     */
    'status'?: BadGatewayErrorAllOfStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BadGatewayErrorAllOf
     */
    'code'?: BadGatewayErrorAllOfCodeEnum;
}

export const BadGatewayErrorAllOfStatusEnum = {
    NUMBER_502: 502
} as const;

export type BadGatewayErrorAllOfStatusEnum = typeof BadGatewayErrorAllOfStatusEnum[keyof typeof BadGatewayErrorAllOfStatusEnum];
export const BadGatewayErrorAllOfCodeEnum = {
    BadGatewayError: 'BadGatewayError'
} as const;

export type BadGatewayErrorAllOfCodeEnum = typeof BadGatewayErrorAllOfCodeEnum[keyof typeof BadGatewayErrorAllOfCodeEnum];


