/* tslint:disable */
/* eslint-disable */
/**
 * ShanyLedger App
 * これはShanyLedgerのAPIサーバーの仕様です。
 *
 * The version of the OpenAPI document: 0.0.9
 * Contact: support@shany-ledger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ConflictErrorAllOf
 */
export interface ConflictErrorAllOf {
    /**
     * 
     * @type {number}
     * @memberof ConflictErrorAllOf
     */
    'status'?: ConflictErrorAllOfStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ConflictErrorAllOf
     */
    'code'?: ConflictErrorAllOfCodeEnum;
}

export const ConflictErrorAllOfStatusEnum = {
    NUMBER_409: 409
} as const;

export type ConflictErrorAllOfStatusEnum = typeof ConflictErrorAllOfStatusEnum[keyof typeof ConflictErrorAllOfStatusEnum];
export const ConflictErrorAllOfCodeEnum = {
    ConflictError: 'ConflictError'
} as const;

export type ConflictErrorAllOfCodeEnum = typeof ConflictErrorAllOfCodeEnum[keyof typeof ConflictErrorAllOfCodeEnum];


