/* tslint:disable */
/* eslint-disable */
/**
 * ShanyLedger App
 * これはShanyLedgerのAPIサーバーの仕様です。
 *
 * The version of the OpenAPI document: 0.0.9
 * Contact: support@shany-ledger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DefaultBadRequestErrorAllOf
 */
export interface DefaultBadRequestErrorAllOf {
    /**
     * 
     * @type {number}
     * @memberof DefaultBadRequestErrorAllOf
     */
    'status'?: DefaultBadRequestErrorAllOfStatusEnum;
}

export const DefaultBadRequestErrorAllOfStatusEnum = {
    NUMBER_400: 400
} as const;

export type DefaultBadRequestErrorAllOfStatusEnum = typeof DefaultBadRequestErrorAllOfStatusEnum[keyof typeof DefaultBadRequestErrorAllOfStatusEnum];


