/* tslint:disable */
/* eslint-disable */
/**
 * ShanyLedger App
 * これはShanyLedgerのAPIサーバーの仕様です。
 *
 * The version of the OpenAPI document: 0.0.9
 * Contact: support@shany-ledger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * @type ForbiddenError
 * サーバーがリクエストを理解したものの、認証が拒否された場合のエラー詳細です。
 * @export
 */
export type ForbiddenError = ForbiddenErrorAllOf & ProblemDetails;


