/* tslint:disable */
/* eslint-disable */
/**
 * ShanyLedger App
 * これはShanyLedgerのAPIサーバーの仕様です。
 *
 * The version of the OpenAPI document: 0.0.8
 * Contact: support@shany-ledger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ForbiddenErrorAllOf
 */
export interface ForbiddenErrorAllOf {
    /**
     * 
     * @type {number}
     * @memberof ForbiddenErrorAllOf
     */
    'status'?: ForbiddenErrorAllOfStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ForbiddenErrorAllOf
     */
    'code'?: ForbiddenErrorAllOfCodeEnum;
}

export const ForbiddenErrorAllOfStatusEnum = {
    NUMBER_403: 403
} as const;

export type ForbiddenErrorAllOfStatusEnum = typeof ForbiddenErrorAllOfStatusEnum[keyof typeof ForbiddenErrorAllOfStatusEnum];
export const ForbiddenErrorAllOfCodeEnum = {
    ForbiddenError: 'ForbiddenError'
} as const;

export type ForbiddenErrorAllOfCodeEnum = typeof ForbiddenErrorAllOfCodeEnum[keyof typeof ForbiddenErrorAllOfCodeEnum];


