/* tslint:disable */
/* eslint-disable */
/**
 * ShanyLedger App
 * これはShanyLedgerのAPIサーバーの仕様です。
 *
 * The version of the OpenAPI document: 0.0.8
 * Contact: support@shany-ledger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * @type GoneError
 * 永久的に利用できなくなっている対象リソースにアクセスしている場合のエラー詳細です。
 * @export
 */
export type GoneError = GoneErrorAllOf & ProblemDetails;


