/* tslint:disable */
/* eslint-disable */
/**
 * ShanyLedger App
 * これはShanyLedgerのAPIサーバーの仕様です。
 *
 * The version of the OpenAPI document: 0.0.9
 * Contact: support@shany-ledger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InternalServerErrorAllOf
 */
export interface InternalServerErrorAllOf {
    /**
     * 
     * @type {number}
     * @memberof InternalServerErrorAllOf
     */
    'status'?: InternalServerErrorAllOfStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof InternalServerErrorAllOf
     */
    'code'?: InternalServerErrorAllOfCodeEnum;
}

export const InternalServerErrorAllOfStatusEnum = {
    NUMBER_500: 500
} as const;

export type InternalServerErrorAllOfStatusEnum = typeof InternalServerErrorAllOfStatusEnum[keyof typeof InternalServerErrorAllOfStatusEnum];
export const InternalServerErrorAllOfCodeEnum = {
    InternalServerError: 'InternalServerError'
} as const;

export type InternalServerErrorAllOfCodeEnum = typeof InternalServerErrorAllOfCodeEnum[keyof typeof InternalServerErrorAllOfCodeEnum];


