/* tslint:disable */
/* eslint-disable */
/**
 * ShanyLedger App
 * これはShanyLedgerのAPIサーバーの仕様です。
 *
 * The version of the OpenAPI document: 0.0.9
 * Contact: support@shany-ledger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MaintenanceAllOf
 */
export interface MaintenanceAllOf {
    /**
     * 
     * @type {string}
     * @memberof MaintenanceAllOf
     */
    'code'?: MaintenanceAllOfCodeEnum;
    /**
     * 
     * @type {number}
     * @memberof MaintenanceAllOf
     */
    'status'?: MaintenanceAllOfStatusEnum;
    /**
     * メンテナンス開始日時
     * @type {string}
     * @memberof MaintenanceAllOf
     */
    'startAt': string;
    /**
     * メンテナンス終了予定日時
     * @type {string}
     * @memberof MaintenanceAllOf
     */
    'endAt': string;
}

export const MaintenanceAllOfCodeEnum = {
    Maintenance: 'Maintenance'
} as const;

export type MaintenanceAllOfCodeEnum = typeof MaintenanceAllOfCodeEnum[keyof typeof MaintenanceAllOfCodeEnum];
export const MaintenanceAllOfStatusEnum = {
    NUMBER_503: 503
} as const;

export type MaintenanceAllOfStatusEnum = typeof MaintenanceAllOfStatusEnum[keyof typeof MaintenanceAllOfStatusEnum];


