/* tslint:disable */
/* eslint-disable */
/**
 * ShanyLedger App
 * これはShanyLedgerのAPIサーバーの仕様です。
 *
 * The version of the OpenAPI document: 0.0.8
 * Contact: support@shany-ledger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NotFoundErrorAllOf
 */
export interface NotFoundErrorAllOf {
    /**
     * 
     * @type {number}
     * @memberof NotFoundErrorAllOf
     */
    'status'?: NotFoundErrorAllOfStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof NotFoundErrorAllOf
     */
    'code'?: NotFoundErrorAllOfCodeEnum;
}

export const NotFoundErrorAllOfStatusEnum = {
    NUMBER_404: 404
} as const;

export type NotFoundErrorAllOfStatusEnum = typeof NotFoundErrorAllOfStatusEnum[keyof typeof NotFoundErrorAllOfStatusEnum];
export const NotFoundErrorAllOfCodeEnum = {
    NotFoundError: 'NotFoundError'
} as const;

export type NotFoundErrorAllOfCodeEnum = typeof NotFoundErrorAllOfCodeEnum[keyof typeof NotFoundErrorAllOfCodeEnum];


