/* tslint:disable */
/* eslint-disable */
/**
 * ShanyLedger App
 * これはShanyLedgerのAPIサーバーの仕様です。
 *
 * The version of the OpenAPI document: 0.0.9
 * Contact: support@shany-ledger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * RFC7807（https://www.rfc-editor.org/rfc/rfc7807）に準拠したエラー詳細のベースです。
 * @export
 * @interface ProblemDetails
 */
export interface ProblemDetails {
    /**
     * エラー内容が判別可能な文字列のコードです。
     * @type {string}
     * @memberof ProblemDetails
     */
    'code': string;
    /**
     * エラーの詳細ドキュメントへのURLです。
     * @type {string}
     * @memberof ProblemDetails
     */
    'type'?: string;
    /**
     * 人間が読むことのできる短いサマリーです。
     * @type {string}
     * @memberof ProblemDetails
     */
    'title': string;
    /**
     * 人間が読むことのできる説明文です。
     * @type {string}
     * @memberof ProblemDetails
     */
    'detail'?: string;
    /**
     * サーバによって生成されたHTTPステータスコードです。
     * @type {number}
     * @memberof ProblemDetails
     */
    'status'?: number;
    /**
     * 問題の発生箇所の参照URIです。
     * @type {string}
     * @memberof ProblemDetails
     */
    'instance'?: string;
}

