/* tslint:disable */
/* eslint-disable */
/**
 * ShanyLedger App
 * これはShanyLedgerのAPIサーバーの仕様です。
 *
 * The version of the OpenAPI document: 0.0.8
 * Contact: support@shany-ledger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Maintenance } from './maintenance';

/**
 * @type ServiceUnavailableError
 * メンテナンスもしくは過負荷等により一時的にサービスが利用できなくなった場合のエラー詳細です。
 * @export
 */
export type ServiceUnavailableError = Maintenance | any;


