/* tslint:disable */
/* eslint-disable */
/**
 * ShanyLedger App
 * これはShanyLedgerのAPIサーバーの仕様です。
 *
 * The version of the OpenAPI document: 0.0.9
 * Contact: support@shany-ledger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TooManyRequestsErrorAllOf
 */
export interface TooManyRequestsErrorAllOf {
    /**
     * 
     * @type {number}
     * @memberof TooManyRequestsErrorAllOf
     */
    'status'?: TooManyRequestsErrorAllOfStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof TooManyRequestsErrorAllOf
     */
    'code'?: TooManyRequestsErrorAllOfCodeEnum;
}

export const TooManyRequestsErrorAllOfStatusEnum = {
    NUMBER_429: 429
} as const;

export type TooManyRequestsErrorAllOfStatusEnum = typeof TooManyRequestsErrorAllOfStatusEnum[keyof typeof TooManyRequestsErrorAllOfStatusEnum];
export const TooManyRequestsErrorAllOfCodeEnum = {
    TooManyRequestsError: 'TooManyRequestsError'
} as const;

export type TooManyRequestsErrorAllOfCodeEnum = typeof TooManyRequestsErrorAllOfCodeEnum[keyof typeof TooManyRequestsErrorAllOfCodeEnum];


