/* tslint:disable */
/* eslint-disable */
/**
 * ShanyLedger App
 * これはShanyLedgerのAPIサーバーの仕様です。
 *
 * The version of the OpenAPI document: 0.0.8
 * Contact: support@shany-ledger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UnauthorizedErrorAllOf
 */
export interface UnauthorizedErrorAllOf {
    /**
     * 
     * @type {number}
     * @memberof UnauthorizedErrorAllOf
     */
    'status'?: UnauthorizedErrorAllOfStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UnauthorizedErrorAllOf
     */
    'code'?: UnauthorizedErrorAllOfCodeEnum;
}

export const UnauthorizedErrorAllOfStatusEnum = {
    NUMBER_401: 401
} as const;

export type UnauthorizedErrorAllOfStatusEnum = typeof UnauthorizedErrorAllOfStatusEnum[keyof typeof UnauthorizedErrorAllOfStatusEnum];
export const UnauthorizedErrorAllOfCodeEnum = {
    UnauthorizedError: 'UnauthorizedError'
} as const;

export type UnauthorizedErrorAllOfCodeEnum = typeof UnauthorizedErrorAllOfCodeEnum[keyof typeof UnauthorizedErrorAllOfCodeEnum];


