/* tslint:disable */
/* eslint-disable */
/**
 * ShanyLedger App
 * これはShanyLedgerのAPIサーバーの仕様です。
 *
 * The version of the OpenAPI document: 0.0.8
 * Contact: support@shany-ledger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ValidationErrorAllOfErrors } from './validation-error-all-of-errors';

/**
 * 
 * @export
 * @interface ValidationErrorAllOf
 */
export interface ValidationErrorAllOf {
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorAllOf
     */
    'code'?: ValidationErrorAllOfCodeEnum;
    /**
     * 
     * @type {Array<ValidationErrorAllOfErrors>}
     * @memberof ValidationErrorAllOf
     */
    'errors'?: Array<ValidationErrorAllOfErrors>;
}

export const ValidationErrorAllOfCodeEnum = {
    ValidationError: 'ValidationError'
} as const;

export type ValidationErrorAllOfCodeEnum = typeof ValidationErrorAllOfCodeEnum[keyof typeof ValidationErrorAllOfCodeEnum];


