/* tslint:disable */
/* eslint-disable */
/**
 * ShanyLedger App
 * これはShanyLedgerのAPIサーバーの仕様です。
 *
 * The version of the OpenAPI document: 0.0.8
 * Contact: support@shany-ledger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ValidationErrorAllOfErrors } from './validation-error-all-of-errors';

/**
 * @type ValidationError
 * バリデーションに失敗した場合のエラー詳細です。
 * @export
 */
export type ValidationError = DefaultBadRequestError & ValidationErrorAllOf;


