/* tslint:disable */
/* eslint-disable */
/**
 * ShanyLedger App
 * これはShanyLedgerのAPIサーバーの仕様です。
 *
 * The version of the OpenAPI document: 0.0.9
 * Contact: support@shany-ledger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { AuthSignupRequest } from '../model';
// @ts-ignore
import { AuthSignupSuccessResponse } from '../model';
// @ts-ignore
import { BadRequestError } from '../model';
// @ts-ignore
import { TooManyRequestsError } from '../model';
/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * メールアドレスとパスワードを使用してサインアップとサインインを行います。
         * @summary サインアップとサインインを行います。
         * @param {AuthSignupRequest} authSignupRequest サインアップのリクエストです。
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signUpWithEmailAndPassword: async (authSignupRequest: AuthSignupRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authSignupRequest' is not null or undefined
            assertParamExists('signUpWithEmailAndPassword', 'authSignupRequest', authSignupRequest)
            const localVarPath = `/signup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(authSignupRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * メールアドレスとパスワードを使用してサインアップとサインインを行います。
         * @summary サインアップとサインインを行います。
         * @param {AuthSignupRequest} authSignupRequest サインアップのリクエストです。
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signUpWithEmailAndPassword(authSignupRequest: AuthSignupRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthSignupSuccessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signUpWithEmailAndPassword(authSignupRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * メールアドレスとパスワードを使用してサインアップとサインインを行います。
         * @summary サインアップとサインインを行います。
         * @param {AuthSignupRequest} authSignupRequest サインアップのリクエストです。
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signUpWithEmailAndPassword(authSignupRequest: AuthSignupRequest, options?: any): AxiosPromise<AuthSignupSuccessResponse> {
            return localVarFp.signUpWithEmailAndPassword(authSignupRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - interface
 * @export
 * @interface AuthApi
 */
export interface AuthApiInterface {
    /**
     * メールアドレスとパスワードを使用してサインアップとサインインを行います。
     * @summary サインアップとサインインを行います。
     * @param {AuthSignupRequest} authSignupRequest サインアップのリクエストです。
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    signUpWithEmailAndPassword(authSignupRequest: AuthSignupRequest, options?: AxiosRequestConfig): AxiosPromise<AuthSignupSuccessResponse>;

}

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI implements AuthApiInterface {
    /**
     * メールアドレスとパスワードを使用してサインアップとサインインを行います。
     * @summary サインアップとサインインを行います。
     * @param {AuthSignupRequest} authSignupRequest サインアップのリクエストです。
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public signUpWithEmailAndPassword(authSignupRequest: AuthSignupRequest, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).signUpWithEmailAndPassword(authSignupRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
