name: Auto Merge

on:
  pull_request_target:
    types:
      - opened
    branches:
      - main

jobs:
  release:
    name: Auto Merge
    runs-on: ubuntu-latest
    # `[automerge]` というprefixがある場合にだけこの workflow が発動する
    if: ${{ startsWith(github.event.pull_request.title, '[automerge]') }}
    steps:
      # API Clientリポジトリ(selfリポジトリ) をチェックアウト
      - name: Checkout Current Repository
        uses: actions/checkout@v3

      - name: Auto Merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge ${{ github.event.pull_request.html_url }} --merge

      # nodeセットアップ
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com

      # npm install と TypeScriptトランスパイルをした後、パッケージとして公開
      - name: build & publish package
        id: publish_package_axios
        run: |
          cd packages/axios
          npm install
          npx tsc
          npm publish ./
          echo ::set-output name=version::$(npm version --json | jq '."@${{ github.repository_owner }}/shany-ledger-api-client-axios"')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
