name: Publish packages

on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  publish:
    name: Build and Publish package
    runs-on: ubuntu-latest
    steps:
      # API Clientリポジトリ(selfリポジトリ) をチェックアウト
      - name: Checkout Current Repository
        uses: actions/checkout@v3

      # nodeセットアップ
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com

      # npm install と TypeScriptトランスパイルをした後、パッケージとして公開
      - name: build & publish package for axios
        id: publish_package_axios
        run: |
          cd packages/axios
          npm install
          npx tsc
          npm publish ./
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
