name: Publish packages

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build and Publish package
    runs-on: ubuntu-latest
    steps:
      # AxiosのAPIクライアントリポジトリ(selfリポジトリ)をチェックアウト
      - name: checkout
        uses: actions/checkout@v3

      # nodeセットアップ
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com

      # npm install と TypeScriptトランスパイルをした後、パッケージとして公開
      - name: build & publish package
        id: publish_package_axios
        run: |
          cd packages/axios
          npm install
          npx tsc
          npm publish ./
          echo ::set-output name=version::$(npm version --json | jq '."@${{ github.repository_owner }}/shany-ledger-api-client-axios"')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
